---
- name: install and configure os centric pieces
  include_tasks: "os_family/{{ ansible_os_family }}.yml"

- name: copy templated config file to /etc/dnf/automatic.conf
  template:
    src: automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    mode: 0644
  notify: reload systemd timer for dnf-automatic

# systemctl enable --now dnf-automatic.timer
- name: enable systemd timer for dnf-automatic
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: yes
